DEBUG: True
SECRET_KEY: 'dev'

AUTH:
  
  USER_SERVICE_NAME: 'cdw'
  SALT: 'salted'

CDW:
  
  MONGODB:
    DB: cdw_flask
    USERNAME: 
    PASSWORD: 
    HOST: localhost
    PORT: 27017
  
  KIOSKS:
    KIOSK_1: '3522755271'
    KIOSK_2: None
    KIOSK_3: None
    KIOSK_4: None
    KIOSK_5: None
    
  TWILIO:
    ACCOUNT_SID: 'AC758bf16fe0a49b5b12dd6d7b2bbf8a73'
    AUTH_TOKEN: 'b58daf22df0816a600dd99abf3d35bd4'
    APP_ID: 'AP05417dd84e5b31bfe413da236755d6de'
    SWITCHBOARD_NUMBER: '+13525052006'
    INCOMING_SMS_COLLECTION: 'smsreceive'
    STATUS_SMS_COLLECTION: 'smsstatus'
  
  FACEBOOK:
    APP_ID: '264488170238614'
    APP_SECRET: 'f2ff313593d664850c028fb1450a09e4'
  
  AWS:
    ACCESS_KEY_ID: AKIAIUP6UG5LN4CTQS7A
    SECRET_ACCESS_KEY: 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
    S3BUCKET: cdw-testing
    
  BEANSTALK:
    HOST: localhost
    PORT: 11300
    
  SMSQUEUE:
    USE: False
    TUBE_NAME: sms_outgoing
  
CDWAPI:
  
  URL_PREFIX: '/api'
  SECRET_KEY: 'secretkey'
